### ISSUE TITLE
Bill of Materials

### ISSUE THREAD

**Issue by exploshot** [dannygrob/OpenWatch#3]
Hello, is the Bill of Materials the same or did you add or change something (except Battery or Screen)?

**Comment by dannygrob** [comment]
Hi!

I added the touchscreen connector for the new screen: DF37NB-10DS-0.4V. 
The rest is the same!

**Comment by exploshot** [comment]
Thank you for your fast answer :)

**Comment by D3M05** [comment]
If you're using the original smarchwatch bom, make sure you purchase the correct 0.39 ohm resistor.  The part number listed in the doc is for a 390 ohm resistor.

**Comment by dannygrob** [comment]
I'll post an updated BOM
